import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-sans">
        <div className="absolute top-1/2 left-1/2 -translate-x-2/4	-translate-y-2/4 ">
          {children}
        </div>
      </body>
    </html>
  );
}
